### ISSUE TITLE
SubViewModel Constructor with runtime data as parameter using factory failed to create

### ISSUE THREAD

**Issue by fengfranklu** [canton7/Stylet#104]
I got stuck to display a subview. It may be something simple. 

My main viewmodel looks like this:
```
public class MainViewModel : Screen
    {
        public PerClassViewModel perclassViewModel { get; set; }

        public MainViewModel(PerClassViewModelFactory perClassViewModelFactory)
        {
            int appid = Properties.Settings.Default.DefaultAppId;
            perclassViewModel = perClassViewModelFactory.GetPerClassViewModel(appid);
        }
}
```

the perClassViewModel is a subviewmodel. It has an integer as a parameter plus a service. So I used a factory for the injection.   

I stepped the code. The mainviewmodel  subviewmodel property is properly initiated in the constructor.  But the following error shows when the code reaches the mainview.
 
StyletIoC.StyletIoCFindConstructorException: 'Unable to find a constructor for type PerClassViewModel which we can call:
Constructor:
   IDataAccessServices: Success
   int: Failure

It looks like it dis-regarded the subviewmodel that has already been created in the constructor, and trying to create a new subviewmodel from the container and fail to find the runtime data to inject. 

I do not know how to fix this.   

My subviewmodel constructor looks like:
`public PerClassViewModel(IDataAccessServices dataAccessServices, int defaultAppId)`

My bootstrapper looks like this:
```
public class BingBingFrontBootstrapper : Bootstrapper<MainViewModel>
    {
        protected override void ConfigureIoC(StyletIoC.IStyletIoCBuilder builder)
        {
            base.ConfigureIoC(builder);

            builder.Bind<IDataAccessServices>().To<BBFDataAccessServices>().InSingletonScope();
            builder.Bind<PerClassViewModelFactory>().ToSelf();
        }       
        
    }

```
It seems should work. 
I appreciate your help.  Thanks.

**Comment by canton7** [comment]
> But the following error shows when the code reaches the mainview.

Which line exactly throws that exception? You said "The mainviewmodel subviewmodel property is properly initiated in the constructor", so it's obviously managing to get to the end of the `MainViewModel`'s constructor. It's not clear to me when it's trying to instantiate a new `PerClassViewModel`.

**Comment by fengfranklu** [comment]
The MainViewModel Constructor went fine. Then to MainView constructor also fine.  Then back to the subview property in MainViewModel see the image below.  This is when I got the error.  
![image](https://user-images.githubusercontent.com/2231559/74671806-f31edc00-5179-11ea-8479-530bcc493f42.png)

the call stack:

This exception was originally thrown at this call stack:
    StyletIoC.Internal.Creators.TypeCreator.GetInstanceExpression(System.Linq.Expressions.ParameterExpression) in TypeCreator.cs
    StyletIoC.Internal.Registrations.TransientRegistration.GetInstanceExpression(System.Linq.Expressions.ParameterExpression) in TransientRegistration.cs
    StyletIoC.Internal.Creators.TypeCreator.GetInstanceExpression.AnonymousMethod__3(System.Reflection.ParameterInfo) in TypeCreator.cs
	System.Linq.Expressions.Expression.New(System.Reflection.ConstructorInfo, System.Collections.Generic.IEnumerable<System.Linq.Expressions.Expression>)
    StyletIoC.Internal.Creators.TypeCreator.GetInstanceExpression(System.Linq.Expressions.ParameterExpression) in TypeCreator.cs
    StyletIoC.Internal.Registrations.TransientRegistration.GetInstanceExpression(System.Linq.Expressions.ParameterExpression) in TransientRegistration.cs
    StyletIoC.Internal.Registrations.RegistrationBase.GetGeneratorInternal() in RegistrationBase.cs

Thanks!

**Comment by canton7** [comment]
That call stack looks truncated. Is there anything you've missed?

**Comment by canton7** [comment]
Can you also post the stack trace which corresponds to your screenshot? I'm trying to figure out how accessing a normal property could possibly be invoking the ioc container

**Comment by canton7** [comment]
Could you please also post your full MainView (xaml and cs) and MainViewModel?

**Comment by fengfranklu** [comment]
StyletIoC.StyletIoCFindConstructorException
  HResult=0x80131500
  Message=Unable to find a constructor for type PerClassViewModel which we can call:
Constructor:
   IDataAccessServices: Success
   int: Failure


  Source=Stylet
  StackTrace:
   at StyletIoC.Internal.Creators.TypeCreator.GetInstanceExpression(ParameterExpression registrationContext) in /_/Stylet/StyletIoC/Internal/Creators/TypeCreator.cs:line 94
   at StyletIoC.Internal.Registrations.TransientRegistration.GetInstanceExpression(ParameterExpression registrationContext) in /_/Stylet/StyletIoC/Internal/Registrations/TransientRegistration.cs:line 15
   at StyletIoC.Internal.Creators.TypeCreator.<>c__DisplayClass6_0.<GetInstanceExpression>b__3(ParameterInfo x) in /_/Stylet/StyletIoC/Internal/Creators/TypeCreator.cs:line 101
   at System.Linq.Enumerable.SelectArrayIterator`2.ToArray()
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at System.Dynamic.Utils.CollectionExtensions.ToReadOnly[T](IEnumerable`1 enumerable)
   at System.Linq.Expressions.Expression.New(ConstructorInfo constructor, IEnumerable`1 arguments)
   at StyletIoC.Internal.Creators.TypeCreator.GetInstanceExpression(ParameterExpression registrationContext) in /_/Stylet/StyletIoC/Internal/Creators/TypeCreator.cs:line 112
   at StyletIoC.Internal.Registrations.TransientRegistration.GetInstanceExpression(ParameterExpression registrationContext) in /_/Stylet/StyletIoC/Internal/Registrations/TransientRegistration.cs:line 15
   at StyletIoC.Internal.Registrations.RegistrationBase.GetGeneratorInternal() in /_/Stylet/StyletIoC/Internal/Registrations/RegistrationBase.cs:line 39
   at StyletIoC.Internal.Registrations.RegistrationBase.GetGenerator() in /_/Stylet/StyletIoC/Internal/Registrations/RegistrationBase.cs:line 31
   at StyletIoC.Internal.Container.Get(RuntimeTypeHandle typeHandle, String key, Type typeIfAvailable) in /_/Stylet/StyletIoC/Internal/Container.cs:line 107
   at StyletIoC.Internal.Container.Get(Type type, String key) in /_/Stylet/StyletIoC/Internal/Container.cs:line 94
   at Stylet.Bootstrapper`1.GetInstance(Type type) in /_/Stylet/Bootstrapper.cs:line 84
   at Stylet.ViewManager.CreateViewForModel(Object model) in /_/Stylet/ViewManager.cs:line 313
   at Stylet.ViewManager.CreateAndBindViewForModel(Object model) in /_/Stylet/ViewManager.cs:line 224
   at Stylet.ViewManager.CreateAndBindViewForModelIfNecessary(Object model) in /_/Stylet/ViewManager.cs:line 211
   at Stylet.ViewManager.OnModelChanged(DependencyObject targetLocation, Object oldValue, Object newValue) in /_/Stylet/ViewManager.cs:line 180
   at Stylet.Xaml.View.<>c.<.cctor>b__10_0(DependencyObject d, DependencyPropertyChangedEventArgs e) in /_/Stylet/Xaml/View.cs:line 106
   at System.Windows.DependencyObject.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   at System.Windows.FrameworkElement.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   at System.Windows.DependencyObject.NotifyPropertyChange(DependencyPropertyChangedEventArgs args)
   at System.Windows.DependencyObject.UpdateEffectiveValue(EntryIndex entryIndex, DependencyProperty dp, PropertyMetadata metadata, EffectiveValueEntry oldEntry, EffectiveValueEntry& newEntry, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType)
   at System.Windows.DependencyObject.InvalidateProperty(DependencyProperty dp, Boolean preserveCurrentValue)
   at System.Windows.DependencyObject.InvalidateProperty(DependencyProperty dp)
   at System.Windows.Data.BindingExpressionBase.Invalidate(Boolean isASubPropertyChange)
   at System.Windows.Data.BindingExpression.TransferValue(Object newValue, Boolean isASubPropertyChange)
   at System.Windows.Data.BindingExpression.Activate(Object item)
   at System.Windows.Data.BindingExpression.AttachToContext(AttachAttempt attempt)
   at System.Windows.Data.BindingExpression.MS.Internal.Data.IDataBindEngineClient.AttachToContext(Boolean lastChance)
   at MS.Internal.Data.DataBindEngine.Task.Run(Boolean lastChance)
   at MS.Internal.Data.DataBindEngine.Run(Object arg)
   at MS.Internal.Data.DataBindEngine.OnLayoutUpdated(Object sender, EventArgs e)
   at System.Windows.ContextLayoutManager.fireLayoutUpdateEvent()
   at System.Windows.ContextLayoutManager.UpdateLayout()
   at System.Windows.UIElement.UpdateLayout()
   at System.Windows.Interop.HwndSource.SetLayoutSize()
   at System.Windows.Interop.HwndSource.set_RootVisualInternal(Visual value)
   at System.Windows.Interop.HwndSource.set_RootVisual(Visual value)
   at System.Windows.Window.SetRootVisual()
   at System.Windows.Window.SetRootVisualAndUpdateSTC()
   at System.Windows.Window.SetupInitialState(Double requestedTop, Double requestedLeft, Double requestedWidth, Double requestedHeight)
   at System.Windows.Window.CreateSourceWindow(Boolean duringShow)
   at System.Windows.Window.CreateSourceWindowDuringShow()
   at System.Windows.Window.SafeCreateWindowDuringShow()
   at System.Windows.Window.ShowHelper(Object booleanBox)
   at System.Windows.Window.Show()
   at Stylet.WindowManager.ShowWindow(Object viewModel, IViewAware ownerViewModel) in /_/Stylet/WindowManager.cs:line 103
   at Stylet.WindowManager.ShowWindow(Object viewModel) in /_/Stylet/WindowManager.cs:line 93
   at Stylet.BootstrapperBase.DisplayRootView(Object rootViewModel) in /_/Stylet/BootstrapperBase.cs:line 102
   at Stylet.Bootstrapper`1.Launch() in /_/Stylet/Bootstrapper.cs:line 93
   at Stylet.BootstrapperBase.Start(String[] args) in /_/Stylet/BootstrapperBase.cs:line 82
   at Stylet.BootstrapperBase.<Setup>b__9_0(Object o, StartupEventArgs e) in /_/Stylet/BootstrapperBase.cs:line 48
   at System.Windows.Application.OnStartup(StartupEventArgs e)
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.Run()
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run()
   at BingBingFront.App.Main()

  This exception was originally thrown at this call stack:
    StyletIoC.Internal.Creators.TypeCreator.GetInstanceExpression(System.Linq.Expressions.ParameterExpression) in TypeCreator.cs
    StyletIoC.Internal.Registrations.TransientRegistration.GetInstanceExpression(System.Linq.Expressions.ParameterExpression) in TransientRegistration.cs
    StyletIoC.Internal.Creators.TypeCreator.GetInstanceExpression.AnonymousMethod__3(System.Reflection.ParameterInfo) in TypeCreator.cs
	System.Linq.Expressions.Expression.New(System.Reflection.ConstructorInfo, System.Collections.Generic.IEnumerable<System.Linq.Expressions.Expression>)
    StyletIoC.Internal.Creators.TypeCreator.GetInstanceExpression(System.Linq.Expressions.ParameterExpression) in TypeCreator.cs
    StyletIoC.Internal.Registrations.TransientRegistration.GetInstanceExpression(System.Linq.Expressions.ParameterExpression) in TransientRegistration.cs
    StyletIoC.Internal.Registrations.RegistrationBase.GetGeneratorInternal() in RegistrationBase.cs
    ...
    [Call Stack Truncated]

**Comment by fengfranklu** [comment]
```
<Window x:Class="BingBingFront.MainView"
             xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
             xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
             xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006" 
              xmlns:s="https://github.com/canton7/Stylet"
             xmlns:d="http://schemas.microsoft.com/expression/blend/2008" 
             
             mc:Ignorable="d" 
             d:DesignHeight="300" d:DesignWidth="300"             
             xmlns:viewModel="clr-namespace:BingBingFront"                     
             d:DataContext="{Binding  Source={d:DesignInstance 
                                      Type=viewModel:MainViewModel, 
                                      IsDesignTimeCreatable=False}}"            
             >

    <Grid>
        <ContentControl s:View.Model="{Binding perclassViewModel}"/>
    </Grid>
    
</Window>

```
This is the MainView

**Comment by fengfranklu** [comment]
This is the main view model:
```
 public class MainViewModel : Screen
    {
        public PerClassViewModel perclassViewModel { get; set; }

        public MainViewModel(PerClassViewModelFactory perClassViewModelFactory)
        {
            int appid = Properties.Settings.Default.DefaultAppId;
            perclassViewModel = perClassViewModelFactory.GetPerClassViewModel(appid);
        }

        public void SaveDefault()
        {
            Properties.Settings.Default.DefaultAppId = perclassViewModel.SelectedClassInfo.LaunchClassId;
        }
    }
```

**Comment by canton7** [comment]
Right, that call stack gives a lot more information on what's going on. It's trying to instantiate the `perClassView`. Can you post that, please.

**Comment by fengfranklu** [comment]
This is the code behind for the main view.
```
 public partial class MainView : Window
    {
       

       // public MainView(MainViewModel vm)
        public MainView()
        {
            InitializeComponent();
            
            //DataContext = vm;
            
            ////Make the first tab selected. 
            //Dispatcher.BeginInvoke((Action)(() => mainTab.SelectedIndex = 1));
        }
    }
```

**Comment by fengfranklu** [comment]
```
 public partial class PerClassView : UserControl
    {
        readonly PerClassViewModel _mainVm;

        public PerClassView( PerClassViewModel mainVm)
        {
            InitializeComponent();
            
            _mainVm = mainVm;
            
            DataContext = _mainVm;

            if (LstBoxMain.Items.SortDescriptions != null)
                LstBoxMain.Items.SortDescriptions.Add(new SortDescription("UiLayer",ListSortDirection.Ascending));
            
            if (LstBoxMain.Items.GroupDescriptions != null)
                LstBoxMain.Items.GroupDescriptions.Add(new PropertyGroupDescription("TheGroup"));
        }

```

**Comment by canton7** [comment]
> public PerClassView( PerClassViewModel mainVm)

There you go.

**Comment by canton7** [comment]
Stylet works by:

1. You create the VM (possibly using the IoC container)
2. Stylet creates the View
3. Stylet binds the View to the VM (by setting the VM as the View's DataContext, and setting the View as the VM's `View` property.

Under VM-first MVVM, your views should not have any direct knowledge of your VMs. Your views should definitely not take VM's as constructor parameters (they should only ever have parameterless constructors). Please see the documentation and samples.

**Comment by fengfranklu** [comment]
Thanks!!!!!  Make sense!
Oh. I forgot to clean the code behind for the subview.  Thanks!!!!
I am trying to convert the app to your framework.  Thanks a million for the great framework.
